tweet/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.index, name='index'),

    url(r'^(?P<profile_id>[0-9]+)/$', views.detail, name='detail'),
]

twitter_trend/urls.py
from django.conf.urls import include, url
from django.contrib import admin



urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^tweet/', include('tweet.urls', namespace="tweet")),
]

tweet/models.py
from django.db import models

class Profile(models.Model):
    profile_name = models.CharField(max_length=500)

    def __str__(self):
        return self.profile_name

class Tweets(models.Model):
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
    text = models.CharField(max_length=500)

    def __str__(self):
        return self.text

tweet/views.py
from django.shortcuts import render, get_object_or_404
from .models import Profile

def index(request):
    object_name = Profile.objects.all()
    return render(request, 'tweet/index.html', {'object_name': object_name})

def detail(request, profile_id):
    profiles = get_object_or_404(Profile, pk=profile_id)
    object_name = Profile.objects.all()
    return render(request, 'tweet/detail.html', {'profiles': profiles, 'object_name': object_name})

tweet/templates/tweet/base.html
<!DOCTYPE html>
<html lang="en">
<head>



    <style>
    div.container {
    height:auto;
    max-width: 100%;
    border: 2px solid gray;
    background:#404643;
}

header, footer {
    font-family: Comic Sans MS;
    padding: 13px;
    color: white;
    background-color: #00aced;
    clear: left;
    text-align: center;
}

nav {
    float: left;
    max-width: 300px;
    margin: 0;
    padding: 2em;
}

nav ul {
    list-style-type: none;
    padding: 0;
}

nav ul a {
    text-decoration: none;
}
article {
    margin-left: 200px;
    padding: 12px;
    overflow: hidden;
    height:auto;
    background-color : white;
 }

p {
    text-transform: uppercase;
    color:black;
    padding:3px;

}

a {
    text-decoration:none;
    color:white;
}
</style>

<body style="height:auto; margin:auto;">

<div class="container">

    <header>
        <h1>TWITTER TREND</h1>
    </header>

{% if object_name %}
       <div style="float : left; padding:15px; margin-top:70px; margin-left:-20px; width:250px; ">
        <ul style="list-style-type: none;">
            {% for profiles in object_name %}
            <li><p title='{{ profiles.profile_name }}'><a href="{% url 'tweet:detail' profiles.id %} ">
                 {{ profiles.profile_name }} </a></p></li>
            {% endfor %}
        </ul>
        </div>
{% else %}
    <h3>No topics to show</h3>>
{% endif %}

{% block body %}
{% endblock %}
</div>

</body>
</html>

tweet/templates/tweet/detail.html
{% extends 'tweet/base.html'%}

{% block body %}

<article>
<h1 style="text-transform: uppercase; text-decoration:underline;
text-align:center; width:78%; color:#404643;">{{ profiles.profile_name }}</h1>

<ul style="list-style-type:none;">
    {% for twit in profiles.tweets_set.all %}
    <li><p style="text-transform: capitalize; padding:2px; border:1px solid black; border-radius:15px;
    width:650px; padding:15px; margin:25px; color:#404643;"> {{ twit.text }} </p></li>
    {% endfor %}
</ul>
</article>

<footer><pre>   DID YOU LIKED IT? :     YES     NO    </pre></footer>
{% endblock %}

tweet/templates/tweet/index.html
<!DOCTYPE html>
<html lang="en">
<head>


<style>
div.container {
    max-width: 100%;
    border: 2px solid gray;
    background:#043057;

}

header, footer {
    padding: 13px;
    color: white;
    background-color: black;
    clear: left;
    text-align: center;
}


article {
    height:auto;
    overflow: hidden;
}

p {
    margin: 40px 40px 40px 40px;
    text-transform: uppercase;
    border:1px solid black;
    border-radius:20px;
    width:230px;
    height:50px;
    padding-top:25px;
    text-align:center;
    background-color:#1dcaff;
    opacity:0.6;
    float : left;
}
p:hover{
    opacity:1;
    color:gray;
}

a{
    color:white;
    text-decoration:none;
}

a:hover {
    opacity:1;
    color:white;
    text-decoration:none;
}


</style>

</head>

<body style="height:auto; margin:auto;">
<div class="container">

    <header>
        <h1>TWITTER TREND</h1>
    </header>
<article>
{% if object_name %}

        <div style="margin:0px 100px 0px 125px; ">

            <div style="margin:50px 30px 70px 30px;">

                {% for profiles in object_name %}
                <p><strong><i><a href="{% url 'tweet:detail' profiles.id %}">
                    {{ profiles.profile_name }} </a></strong></i></p>
                {% endfor %}
            </div>

        </div>

{% else %}
    <h3>No topics to show</h3>>
{% endif %}
</article>

<footer> CREDITS => MADE BY DEEP AND SHYAMAL @2017</footer>

</div>
</body>
</html>